// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TriBalance.Infrastructure.Persistence.PostgreSQL;

#nullable disable

namespace TriBalance.Infrastructure.Persistence.PostgreSQL.Migrations
{
    [DbContext(typeof(TriBalanceDbContext))]
    [Migration("20260413194030_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TriBalance.Domain.Engagement.Engagement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("FiscalYearEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fiscal_year_end");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("engagements", (string)null);
                });

            modelBuilder.Entity("TriBalance.Domain.Engagement.GLEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_code");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_name");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("balance");

                    b.Property<decimal>("Credit")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("credit");

                    b.Property<decimal>("Debit")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("debit");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<Guid>("TrialBalanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("trial_balance_id");

                    b.HasKey("Id");

                    b.HasIndex("EngagementId")
                        .HasDatabaseName("idx_gl_entries_engagement");

                    b.HasIndex("TrialBalanceId")
                        .HasDatabaseName("idx_gl_entries_trial_balance");

                    b.ToTable("gl_entries", (string)null);
                });

            modelBuilder.Entity("TriBalance.Domain.Engagement.TrialBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("TotalCredits")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_credits");

                    b.Property<decimal>("TotalDebits")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_debits");

                    b.HasKey("Id");

                    b.HasIndex("EngagementId");

                    b.ToTable("trial_balances", (string)null);
                });

            modelBuilder.Entity("TriBalance.Domain.Validation.ValidationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Queued")
                        .HasColumnName("status");

                    b.Property<Guid>("TrialBalanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("trial_balance_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("EngagementId")
                        .HasDatabaseName("idx_validation_jobs_engagement");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_validation_jobs_status");

                    b.ToTable("validation_jobs", (string)null);
                });

            modelBuilder.Entity("TriBalance.Domain.Engagement.GLEntry", b =>
                {
                    b.HasOne("TriBalance.Domain.Engagement.TrialBalance", null)
                        .WithMany("GlEntries")
                        .HasForeignKey("TrialBalanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TriBalance.Domain.Engagement.TrialBalance", b =>
                {
                    b.HasOne("TriBalance.Domain.Engagement.Engagement", null)
                        .WithMany("TrialBalances")
                        .HasForeignKey("EngagementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TriBalance.Domain.Engagement.Engagement", b =>
                {
                    b.Navigation("TrialBalances");
                });

            modelBuilder.Entity("TriBalance.Domain.Engagement.TrialBalance", b =>
                {
                    b.Navigation("GlEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
